ActiveAdmin.register Chiffre do

  # See permitted parameters documentation:
  # https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters
  #
  # Uncomment all parameters which should be permitted for assignment
  #
  permit_params :organisme_id, :exercice_budgetaire, :type_budget, :phase, :statut, :commentaire, :comptabilite_budgetaire, :operateur, :user_id, :emplois_plafond, :emplois_hors_plafond, :emplois_total, :emplois_plafond_rappel, :emplois_plafond_prenotifie, :emplois_schema, :emplois_schema_prenotifie, :emplois_non_remuneres, :emplois_titulaires, :emplois_titulaires_montant, :emplois_contractuels, :emplois_contractuels_montant, :emplois_autre_entite, :emplois_depenses_personnel, :emplois_charges_personnel, :credits_ae_total, :credits_ae_fonctionnement, :credits_ae_intervention, :credits_ae_investissement, :credits_cp_total, :credits_cp_fonctionnement, :credits_cp_intervention, :credits_cp_investissement, :credits_cp_operations, :credits_cp_recettes_flechees, :credits_subvention_sp, :credits_subvention_investissement_globalisee, :credits_subvention_investissement_flechee, :credits_financements_etat_autres, :credits_financements_etat_fleches, :credits_fiscalite_affectee, :credits_financements_publics_autres, :credits_financements_publics_fleches, :credits_recettes_propres_globalisees, :credits_recettes_propres_flechees, :credits_restes_a_payer, :tresorerie_finale_flechee, :tresorerie_finale_non_flechee, :tresorerie_finale, :tresorerie_variation, :tresorerie_variation_flechee, :tresorerie_variation_non_flechee, :tresorerie_min, :tresorerie_max, :tresorerie_min_date, :tresorerie_max_date, :commentaire_annexe, :capacite_autofinancement, :fonds_roulement_final, :fonds_roulement_variation, :fonds_roulement_besoin_final, :risque_insolvabilite, :charges_fonctionnement, :charges_intervention, :charges_non_decaissables, :produits_subventions_etat, :produits_fiscalite_affectee, :produits_subventions_autres, :produits_autres, :produits_non_encaissables, :emplois_cout_total, :emplois_cout_investissements, :ressources_financement_etat, :ressources_autres, :decaissements_emprunts, :encaissements_emprunts, :decaissements_operations, :encaissements_operations, :decaissements_autres, :encaissements_autres, :ressources_total
  #
  # or
  #
  # permit_params do
  #   permitted = [:organisme_id, :exercice_budgetaire, :type_budget, :phase, :statut, :commentaire, :comptabilite_budgetaire, :operateur, :user_id, :emplois_plafond, :emplois_hors_plafond, :emplois_total, :emplois_plafond_rappel, :emplois_plafond_prenotifie, :emplois_schema, :emplois_schema_prenotifie, :emplois_non_remuneres, :emplois_titulaires, :emplois_titulaires_montant, :emplois_contractuels, :emplois_contractuels_montant, :emplois_autre_entite, :emplois_depenses_personnel, :emplois_charges_personnel, :credits_ae_total, :credits_ae_fonctionnement, :credits_ae_intervention, :credits_ae_investissement, :credits_cp_total, :credits_cp_fonctionnement, :credits_cp_intervention, :credits_cp_investissement, :credits_cp_operations, :credits_cp_recettes_flechees, :credits_subvention_sp, :credits_subvention_investissement_globalisee, :credits_subvention_investissement_flechee, :credits_financements_etat_autres, :credits_financements_etat_fleches, :credits_fiscalite_affectee, :credits_financements_publics_autres, :credits_financements_publics_fleches, :credits_recettes_propres_globalisees, :credits_recettes_propres_flechees, :credits_restes_a_payer, :tresorerie_finale_flechee, :tresorerie_finale_non_flechee, :tresorerie_finale, :tresorerie_variation, :tresorerie_variation_flechee, :tresorerie_variation_non_flechee, :tresorerie_min, :tresorerie_max, :tresorerie_min_date, :tresorerie_max_date, :commentaire_annexe, :capacite_autofinancement, :fonds_roulement_final, :fonds_roulement_variation, :fonds_roulement_besoin_final, :risque_insolvabilite, :charges_fonctionnement, :charges_intervention, :charges_non_decaissables, :produits_subventions_etat, :produits_fiscalite_affectee, :produits_subventions_autres, :produits_autres, :produits_non_encaissables, :emplois_cout_total, :emplois_cout_investissements, :ressources_financement_etat, :ressources_autres, :decaissements_emprunts, :encaissements_emprunts, :decaissements_operations, :encaissements_operations, :decaissements_autres, :encaissements_autres, :ressources_total]
  #   permitted << :other if params[:action] == 'create' && current_user.admin?
  #   permitted
  # end
  
end
